/*
###############################
# Copyright (C) 2012 Jon Schang
# 
# This file is part of jSchangLib, released under the LGPLv3
# 
# jSchangLib is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# jSchangLib is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with jSchangLib.  If not, see <http://www.gnu.org/licenses/>.
###############################
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.08 at 09:03:52 PM EST 
//


package com.jonschang.cluster.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommandRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommandRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originNodeId" type="{http://model.cluster.jonschang.com/Cluster}NodeId" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="springCommand" type="{http://model.cluster.jonschang.com/Cluster}SpringCommand"/>
 *           &lt;element name="shellCommand" type="{http://model.cluster.jonschang.com/Cluster}ShellCommand"/>
 *           &lt;element name="factoryMethodCommand" type="{http://model.cluster.jonschang.com/Cluster}FactoryMethodCommand"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="mode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="async"/>
 *             &lt;enumeration value="sync"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommandRequest", propOrder = {
    "originNodeId",
    "springCommand",
    "shellCommand",
    "factoryMethodCommand"
})
public class CommandRequest {

    protected NodeId originNodeId;
    protected SpringCommand springCommand;
    protected ShellCommand shellCommand;
    protected FactoryMethodCommand factoryMethodCommand;
    @XmlAttribute(required = true)
    protected String mode;

    /**
     * Gets the value of the originNodeId property.
     * 
     * @return
     *     possible object is
     *     {@link NodeId }
     *     
     */
    public NodeId getOriginNodeId() {
        return originNodeId;
    }

    /**
     * Sets the value of the originNodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeId }
     *     
     */
    public void setOriginNodeId(NodeId value) {
        this.originNodeId = value;
    }

    /**
     * Gets the value of the springCommand property.
     * 
     * @return
     *     possible object is
     *     {@link SpringCommand }
     *     
     */
    public SpringCommand getSpringCommand() {
        return springCommand;
    }

    /**
     * Sets the value of the springCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpringCommand }
     *     
     */
    public void setSpringCommand(SpringCommand value) {
        this.springCommand = value;
    }

    /**
     * Gets the value of the shellCommand property.
     * 
     * @return
     *     possible object is
     *     {@link ShellCommand }
     *     
     */
    public ShellCommand getShellCommand() {
        return shellCommand;
    }

    /**
     * Sets the value of the shellCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShellCommand }
     *     
     */
    public void setShellCommand(ShellCommand value) {
        this.shellCommand = value;
    }

    /**
     * Gets the value of the factoryMethodCommand property.
     * 
     * @return
     *     possible object is
     *     {@link FactoryMethodCommand }
     *     
     */
    public FactoryMethodCommand getFactoryMethodCommand() {
        return factoryMethodCommand;
    }

    /**
     * Sets the value of the factoryMethodCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link FactoryMethodCommand }
     *     
     */
    public void setFactoryMethodCommand(FactoryMethodCommand value) {
        this.factoryMethodCommand = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

}
