/*
###############################
# Copyright (C) 2012 Jon Schang
# 
# This file is part of jSchangLib, released under the LGPLv3
# 
# jSchangLib is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# jSchangLib is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with jSchangLib.  If not, see <http://www.gnu.org/licenses/>.
###############################
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.08 at 09:03:52 PM EST 
//


package com.jonschang.cluster.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jonschang.cluster.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jonschang.cluster.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpringCommand.Configuration }
     * 
     */
    public SpringCommand.Configuration createSpringCommandConfiguration() {
        return new SpringCommand.Configuration();
    }

    /**
     * Create an instance of {@link CommandId }
     * 
     */
    public CommandId createCommandId() {
        return new CommandId();
    }

    /**
     * Create an instance of {@link MethodCall }
     * 
     */
    public MethodCall createMethodCall() {
        return new MethodCall();
    }

    /**
     * Create an instance of {@link SpringCommand }
     * 
     */
    public SpringCommand createSpringCommand() {
        return new SpringCommand();
    }

    /**
     * Create an instance of {@link Authorization }
     * 
     */
    public Authorization createAuthorization() {
        return new Authorization();
    }

    /**
     * Create an instance of {@link NodeInfo }
     * 
     */
    public NodeInfo createNodeInfo() {
        return new NodeInfo();
    }

    /**
     * Create an instance of {@link CommandInfo }
     * 
     */
    public CommandInfo createCommandInfo() {
        return new CommandInfo();
    }

    /**
     * Create an instance of {@link ThreeFloatUsageInfo }
     * 
     */
    public ThreeFloatUsageInfo createThreeFloatUsageInfo() {
        return new ThreeFloatUsageInfo();
    }

    /**
     * Create an instance of {@link NodeId }
     * 
     */
    public NodeId createNodeId() {
        return new NodeId();
    }

    /**
     * Create an instance of {@link TerminationNotification }
     * 
     */
    public TerminationNotification createTerminationNotification() {
        return new TerminationNotification();
    }

    /**
     * Create an instance of {@link CommandRequest }
     * 
     */
    public CommandRequest createCommandRequest() {
        return new CommandRequest();
    }

    /**
     * Create an instance of {@link NodeInfo.Commands }
     * 
     */
    public NodeInfo.Commands createNodeInfoCommands() {
        return new NodeInfo.Commands();
    }

    /**
     * Create an instance of {@link NodeInfo.ChildNodes }
     * 
     */
    public NodeInfo.ChildNodes createNodeInfoChildNodes() {
        return new NodeInfo.ChildNodes();
    }

    /**
     * Create an instance of {@link FactoryMethodCommand }
     * 
     */
    public FactoryMethodCommand createFactoryMethodCommand() {
        return new FactoryMethodCommand();
    }

    /**
     * Create an instance of {@link NodeInfo.ServiceInfo }
     * 
     */
    public NodeInfo.ServiceInfo createNodeInfoServiceInfo() {
        return new NodeInfo.ServiceInfo();
    }

    /**
     * Create an instance of {@link ShellCommand }
     * 
     */
    public ShellCommand createShellCommand() {
        return new ShellCommand();
    }

    /**
     * Create an instance of {@link NodeConfiguration }
     * 
     */
    public NodeConfiguration createNodeConfiguration() {
        return new NodeConfiguration();
    }

    /**
     * Create an instance of {@link CommandAcceptedNotification }
     * 
     */
    public CommandAcceptedNotification createCommandAcceptedNotification() {
        return new CommandAcceptedNotification();
    }

}
