/*
###############################
# Copyright (C) 2012 Jon Schang
# 
# This file is part of jSchangLib, released under the LGPLv3
# 
# jSchangLib is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# jSchangLib is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with jSchangLib.  If not, see <http://www.gnu.org/licenses/>.
###############################
*/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.08 at 09:03:52 PM EST 
//


package com.jonschang.cluster.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThreeFloatUsageInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThreeFloatUsageInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="one" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="five" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="fifteen" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThreeFloatUsageInfo")
public class ThreeFloatUsageInfo {

    @XmlAttribute(required = true)
    protected float one;
    @XmlAttribute(required = true)
    protected float five;
    @XmlAttribute(required = true)
    protected float fifteen;

    /**
     * Gets the value of the one property.
     * 
     */
    public float getOne() {
        return one;
    }

    /**
     * Sets the value of the one property.
     * 
     */
    public void setOne(float value) {
        this.one = value;
    }

    /**
     * Gets the value of the five property.
     * 
     */
    public float getFive() {
        return five;
    }

    /**
     * Sets the value of the five property.
     * 
     */
    public void setFive(float value) {
        this.five = value;
    }

    /**
     * Gets the value of the fifteen property.
     * 
     */
    public float getFifteen() {
        return fifteen;
    }

    /**
     * Sets the value of the fifteen property.
     * 
     */
    public void setFifteen(float value) {
        this.fifteen = value;
    }

}
